# Generated by Django 4.1.7 on 2023-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videocategorie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='front_img',
            field=models.ImageField(default=1, upload_to='video'),
            preserve_default=False,
        ),
    ]
