# Generated by Django 4.1.7 on 2023-03-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_video_front_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='front_img',
            field=models.ImageField(upload_to='video_front_images'),
        ),
    ]
