# Generated by Django 4.1.7 on 2023-03-13 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_video_front_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('discription', models.TextField(verbose_name="Bosh shifokor ma'lumotlari")),
            ],
            options={
                'verbose_name': 'Bosh shifokor',
                'verbose_name_plural': 'Bosh shifokorlar',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ('id',), 'verbose_name': 'Klinika', 'verbose_name_plural': 'Klinikalar'},
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('discription', models.TextField(verbose_name="Hamshira ma'lumotlari")),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.clinic', verbose_name='Qaysi kilnika shifokori')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.leaderdoctor', verbose_name='Vrach')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hamshirani tanlang')),
            ],
            options={
                'verbose_name': 'Hamshira',
                'verbose_name_plural': 'Hamshiralar',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='leaderdoctor',
            name='clinica',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='home.clinic', verbose_name='Qaysi klinika bosh shifokori'),
        ),
        migrations.AddField(
            model_name='leaderdoctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bosh shifokorni tanlang'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('discription', models.TextField(verbose_name="Bosh shifokor ma'lumotlari")),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.clinic', verbose_name='Qaysi kilnika shifokori')),
                ('leader_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.leaderdoctor', verbose_name='Bosh vrach')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctorni tanlang')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ('id',),
            },
        ),
    ]
