# Generated by Django 4.1.7 on 2023-03-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clinic_leader',
        ),
        migrations.AddField(
            model_name='user',
            name='disabiltiy',
            field=models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=20, null=True, verbose_name='Nogironligi bormi'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('first', '1-gruh'), ('second', '2-gruh'), ('third', '3-gruh'), ('fourth', '4-gruh')], max_length=20, null=True, verbose_name='Qaysi gruxga kiradi'),
        ),
        migrations.AddField(
            model_name='user',
            name='iron_notebook',
            field=models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=255, null=True, verbose_name='Temir daftarda bormi'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=20, null=True, verbose_name='Pasport seriyasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='womens_notebook',
            field=models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=20, null=True, verbose_name='Ayollar daftarida bormi'),
        ),
    ]
