# Generated by Django 4.1.7 on 2023-03-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_clinic_leader_user_disabiltiy_user_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='young_notebook',
            field=models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=20, null=True, verbose_name='Yoshlar daftarida bormi'),
        ),
    ]
